version: "3.8"

# Common Environment Variables (Shared Configuration Block)
x-common-env: &common-env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

# Define the network for all services
networks:
  default:
    external: true
    name: ${HOMELAB_NETWORK}
