version: "3.8"

services:
  # -----------------------------------------------------------
  # IMMICH SERVER & UI
  # -----------------------------------------------------------
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
      - immich-machine-learning
    restart: always
    healthcheck:
      disable: false

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    depends_on:
      - immich-server
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - .env
    volumes:
      - immich-model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      disable: false

  # -----------------------------------------------------------
  # IMMICH DEPENDENCIES
  # -----------------------------------------------------------
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
    volumes:
      - ${DOCKER_CONFIG_BASE}/immich/redis:/data 
      - /etc/localtime:/etc/localtime:ro
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    shm_size: 128mb
    restart: always

volumes:
  immich-model-cache:
