version: "3.8"

services:
  # -----------------------------------------------------------
  # IMMICH (Self-hosted Photo/Video Backup)
  # -----------------------------------------------------------
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    env_file: .env
    environment:
      # Inherit common environment variables
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      # Immich Specific Env
      DB_HOSTNAME: immich-database
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      REDIS_HOSTNAME: immich-redis
      REDIS_PASSWORD: ${IMMICH_REDIS_PASSWORD}
      IMMICH_WEB_URL: http://localhost:${IMMICH_HOST_PORT}
    volumes:
      - ${DOCKER_CONFIG_BASE}/immich/config:/usr/src/app/config
      - ${DATA_STORAGE_BASE}/immich/upload:/usr/src/app/upload
    ports:
      - "${IMMICH_HOST_PORT}:3001"
    depends_on:
      - immich-database
      - immich-redis
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-microservices:${IMMICH_VERSION}
    container_name: immich-microservices
    env_file: .env
    environment:
      # Inherit common environment variables
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DB_HOSTNAME: immich-database
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      REDIS_HOSTNAME: immich-redis
      REDIS_PASSWORD: ${IMMICH_REDIS_PASSWORD}
    volumes:
      - ${DATA_STORAGE_BASE}/immich/upload:/usr/src/app/upload
    depends_on:
      - immich-database
      - immich-redis
    restart: always

  immich-database:
    image: postgres:15-alpine
    container_name: immich-database
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_DB: immich
    volumes:
      - ${DOCKER_CONFIG_BASE}/immich/database:/var/lib/postgresql/data
    restart: always

  immich-redis:
    image: redis:6.2-alpine
    container_name: immich-redis
    env_file: .env
    environment:
      REDIS_PASSWORD: ${IMMICH_REDIS_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_BASE}/immich/redis:/data
    command: redis-server --requirepass ${IMMICH_REDIS_PASSWORD}
    restart: always
