version: "3.8"

services:

  # -----------------------------------------------------------
  # AUTOMATED MEDIA MANAGEMENT (The 'Arr' Stack)
  # -----------------------------------------------------------
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: .env
    environment:
      <<: *common-env
      WEBUI_PORT: "8083"
    volumes:
      - ${DOCKER_CONFIG_BASE}/qbit:/config
      - ${DATA_STORAGE_BASE}/download:/downloads
    ports:
      - "${QBITTORRENT_HOST_PORT_WEBUI}:8083"
      - "${QBITTORRENT_HOST_PORT_TRANSFERS}:6881"
      - "${QBITTORRENT_HOST_PORT_TRANSFERS}:6881/udp"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file: .env
    environment: *common-env
    volumes:
      - ${DOCKER_CONFIG_BASE}/prowlarr:/config
    ports:
      - "${PROWLARR_HOST_PORT}:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file: .env
    environment: *common-env
    volumes:
      - ${DOCKER_CONFIG_BASE}/radarr:/config
      - ${DATA_STORAGE_BASE}/download:/downloads
      - ${DATA_STORAGE_BASE}/media/movies:/movies
    ports:
      - "${RADARR_HOST_PORT}:7878"
    depends_on: [qbittorrent, prowlarr]
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file: .env
    environment: *common-env
    volumes:
      - ${DOCKER_CONFIG_BASE}/sonarr:/config
      - ${DATA_STORAGE_BASE}/download:/downloads
      - ${DATA_STORAGE_BASE}/media/tvshow:/tv
    ports:
      - "${SONARR_HOST_PORT}:8989"
    depends_on: [qbittorrent, prowlarr]
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    env_file: .env
    environment: *common-env
    volumes:
      - ${DOCKER_CONFIG_BASE}/bazarr:/config
      - ${DATA_STORAGE_BASE}/media/movies:/movies
      - ${DATA_STORAGE_BASE}/media/tvshow:/tv
    ports:
      - "${BAZARR_HOST_PORT}:6767"
    depends_on: [radarr, sonarr]
    restart: unless-stopped
